{{- if eq (include "forge.createSecret" . ) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: flowfuse-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "forge.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if (include "forge.postgresqlPasswords" . | trim) }}
  {{- include "forge.postgresqlPasswords" . | nindent 2 -}}
  {{- end }}
  {{- if (include "forge.smtpPassword" . | trim) }}
  {{- include "forge.smtpPassword" . | nindent 2 -}}
  {{- end }}
  {{- if (include "forge.assistantToken" . | trim) }}
  {{- include "forge.assistantToken" . | nindent 2 -}}
  {{- end }}
  {{- if (include "forge.expertToken" . | trim) }}
  {{- include "forge.expertToken" . | nindent 2 -}}
  {{- end }}
{{- end }}