{{- $forgeHostname := or (.Values.forge.entryPoint) (printf "%s%s" "forge." .Values.forge.domain) -}}
apiVersion: v1
kind: Service
metadata:
  name: forge
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "forge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.forge.service.type }}
  selector:
    {{- include "forge.forgeSelectorLabels" . | nindent 6 }}
  {{- if eq .Values.forge.service.type "NodePort" }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    {{- if .Values.forge.service.nodePort }}
    nodePort: {{ .Values.forge.service.nodePort }}
    {{- end }}
  {{- else }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowforge-ingress
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "forge.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.certManagerIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManagerIssuer }}
  {{- end }}
  {{- $filteredAnnotations := include "forge.filteredIngressAnnotations" . | replace "{{ instanceHost }}" $forgeHostname | replace "{{ serviceName }}" "forge" }}
  {{- if $filteredAnnotations }}
{{ $filteredAnnotations | indent 4 }}
  {{- end }}
spec:
  {{- if and $.Values.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
  - host: {{ $forgeHostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: forge
            port:
              number: 80
  {{- if include "forge.certManagerEnabled" . }}
  tls:
  - hosts:
    - {{ $forgeHostname }}
    secretName: {{ $forgeHostname }}
  {{- end }}
{{- if gt (int .Values.forge.replicas) 1 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowforge-ingress-api-devices
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "forge.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.certManagerIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManagerIssuer }}
  {{- end }}
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-name: FFSESSION
    nginx.ingress.kubernetes.io/session-cookie-samesite: Strict
  {{- $filteredAnnotations := include "forge.filteredIngressAnnotations" . | replace "{{ instanceHost }}" $forgeHostname | replace "{{ serviceName }}" "forge" }}
  {{- if $filteredAnnotations }}
{{ $filteredAnnotations | indent 4 }}
  {{- end }}
spec:
  {{- if and $.Values.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
  - host: {{ $forgeHostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/api/v1/devices/"
        backend:
          service:
            name: forge
            port:
              number: 80
  {{- if include "forge.certManagerEnabled" . }}
  tls:
  - hosts:
    - {{ $forgeHostname }}
    secretName: {{ $forgeHostname }}
  {{- end }}
{{- end -}}