apiVersion: "v2"
name: "flowforge"
version: "1.3.3"
description: "FlowForge"
type: "application"
home: "https://flowforge.com"
icon: "https://flowforge.com/apple-touch-icon.png"
keywords:
  - flowforge
  - node-red
dependencies:
  - name: postgresql
    version: 10.14.0
    repository: https://charts.bitnami.com/bitnami
    condition: forge.localPostgresql
maintainers:
  - name: "FlowForge Inc"
    url: "https://flowforge.com"
appVersion: "1.3.3"
